# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34be5f44ebcc9c8c9a4d5e2cc09280a3652d261feb2058a878727bebacb4458da9746d6dc46b55925bcfd5bc23c50b1a3d5b124b0156f9b55dbaa2c45ec930be

test:
  secret_key_base: 7b597903fb5eb3958d7a75bfd968a43b70440ace2a800483c2de099f10d7c3de7fedcb2fb31a289105c2ab2e6fe8c43d324f2c320917c09930073608a1545824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
